FROM nvcr.io/nvidia/l4t-base:r32.4.4

ARG DEBIAN_FRONTEND=noninteractive

ENV TZ=Europe

RUN apt-get update

RUN apt-get install -y libgstreamer1.0-dev \
	libgstreamer-plugins-base1.0-dev \
	libgstreamer-plugins-bad1.0-dev \
	gstreamer1.0-plugins-base \
	gstreamer1.0-plugins-good \
	gstreamer1.0-plugins-bad \
	gstreamer1.0-plugins-ugly \
	gstreamer1.0-libav \
	gstreamer1.0-doc \
	gstreamer1.0-tools \
	gstreamer1.0-x \
	gstreamer1.0-alsa \
	gstreamer1.0-gl \
	gstreamer1.0-gtk3 \
	gstreamer1.0-qt5 \ 
	gstreamer1.0-pulseaudio

# ENV GST_DEBUG=4

CMD gst-launch-1.0 -e v4l2src device=/dev/video0 \
					! video/x-raw,height=1080,width=1920,framerate=5/1,format=YUY2 \
					! decodebin \
					! videoconvert \
					! tee name=t \
						t. \
							! queue \
							! nvvidconv \
							! 'video/x-raw(memory:NVMM), format=I420, width=1920, height=1080' \
							! nvv4l2h264enc \
							! rtph264pay \
							! udpsink host=detector port=6000 sync=false \
						t. \
							! queue \
							! matroskamux \
							! filesink location=/media/video-raw-file.mkv

