FROM ubuntu:18.04

ARG DEBIAN_FRONTEND=noninteractive

ENV TZ=Europe

RUN apt-get update
 

RUN apt-get install -y libgstreamer1.0-dev \
	libgstreamer-plugins-base1.0-dev \
	libgstreamer-plugins-bad1.0-dev \
	gstreamer1.0-plugins-base \
	gstreamer1.0-plugins-good \
	gstreamer1.0-plugins-bad \
	gstreamer1.0-plugins-ugly \
	gstreamer1.0-libav \
	gstreamer1.0-doc \
	gstreamer1.0-tools \
	gstreamer1.0-x \
	gstreamer1.0-alsa \
	gstreamer1.0-gl \
	gstreamer1.0-gtk3 \
	gstreamer1.0-qt5 \ 
	gstreamer1.0-pulseaudio

WORKDIR /code

ENV GST_DEBUG=4

CMD gst-launch-1.0 -e v4l2src device=/dev/video0 ! video/x-raw,height=360,width=640,framerate=30/1,format=YUY2 ! decodebin ! videoconvert ! tee name=t \
						t. ! queue ! x264enc tune=zerolatency ! rtph264pay ! udpsink host=detector port=6000 sync=false \
						t. ! queue ! filesink location=/media/video-raw-file.YUY2

